### ISSUE TITLE
Typings install fails.

### ISSUE THREAD

**Issue by mko** [manekinekko/angular2-dependencies-graph#12]
The `npm typings` script has a typo.

Currently, it read `typings install --ambiant`

It should read `typings install --ambient`

**Comment by mko** [comment]
This will also need to be pushed to NPM after it's fixed.

**Comment by mko** [comment]
I take it back. It's a deeper issue. The typo is still a valid fix, but the issue actually revolves around `configstore` trying to access `~/.config/configstore/typings.json` and there being an innate permissions issue there, even installing with `sudo`.

**Comment by mko** [comment]
The error itself:

```
> angular2-dependencies-graph@0.2.6 typings /usr/local/lib/node_modules/angular2-dependencies-graph
> typings install --ambient

/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/mko/.config/configstore/typings.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.create.all.get (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/configstore/index.js:28:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular2-dependencies-graph/node_modules/typings-core/dist/utils/store.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

It should be noted that simply changing the `typings.json` file in `~/.config/configstore/` to read/writable doesn't fix the issue.

**Comment by mko** [comment]
It looks like you have to set the entire `.config` directory to read/writable. Might be worth looking for an alternative to `configstore`.

**Comment by kushwahashiv** [comment]
This creating trouble suddenly after upgrading it to typings version

**Comment by manekinekko** [comment]
this issue seems to be related to typings. See related issue https://github.com/typings/typings/issues/269
